version: '3.8'

services:
  webmvc:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./api:/app
    command: dotnet watch --project ./app run --urls "http://0.0.0.0:5000" 
    ports:
      - 5000:5000

